defaults: &defaults
  docker:
    - image: circleci/elixir:1.9.1

    - image: postgres:11-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ""

  environment:
    MIX_ENV: test
    MIX_HOME: /home/circleci/app/global

  working_directory: ~/app

version: 2
jobs:
  checkout_code:
    <<: *defaults

    steps:
      - checkout

      - persist_to_workspace:
          root: .
          paths:
          - .

  install_dependencies:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install Hex Locally
          command: mix local.hex --force

      - run:
          name: Install Rebar
          command: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}--{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache

      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run:
          name: Install and Compile Project Dependencies
          command: mix do deps.get, deps.compile

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}--{{ checksum "mix.lock" }}
          paths:
            - "deps"

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths:
            - "deps"

      - save_cache:
          key: v1-mix-cache
          paths:
            - "deps"
            - "~/.mix"

      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"

      - save_cache:
          key: v1-build-cache
          paths: "_build"

      - persist_to_workspace:
          root: .
          paths:
            - .

  set_up_environment:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Set Up Database
          command: mix ecto.create

      - persist_to_workspace:
          root: .
          paths:
            - .

  lint_project:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Lint Project
          command: mix lint

      - run:
          name: Generate file for checksum
          command: cat mix.exs mix.lock .dialyzer_ignore.exs > dialyzer-checksummable

      - restore_cache:
          keys:
            - v2-plt--{{ checksum "dialyzer-checksummable" }}

      - run:
          name: Type Check
          command: MIX_ENV=dev mix dialyzer --halt-exit-status

      - save_cache:
          key: v2-plt--{{checksum "mix.lock" }}
          paths:
            - priv/plts

  run_tests:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Run General Tests
          command: mix test

      - store_test_results:
          path: "_build/test/lib/figgis"

workflows:
  version: 2

  test_and_deploy:
    jobs:
      - checkout_code

      - install_dependencies:
          requires:
            - checkout_code

      - set_up_environment:
          requires:
            - install_dependencies

      - lint_project:
          requires:
            - set_up_environment

      - run_tests:
          requires:
            - set_up_environment
